include:
  - compose-base.yaml

name: frr

services:
  news-app:
    build:
      context: ../..
      dockerfile: ./deploy/docker/app/Dockerfile
    container_name: frr-news-app
    depends_on:
      news-storage:
        condition: service_started
        # condition: service_healthy
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://$${APP_HOST}:$${APP_PORT}/ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 0s
    networks:
      - news-storage
      - news-public
    ports:
      - "4000:4000"
    read_only: true
    restart: unless-stopped

  news-storage:
    container_name: frr-news-storage
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent",  "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 0s
    image: mysql:latest
    networks:
      - news-storage
    restart: unless-stopped
    volumes:
      - ./storage/initdb:/docker-entrypoint-initdb.d
